os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.4.0"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
branches:
  only:
  - develop
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install @angular/cli -g
install:
  - npm install
script:
  - ng test --watch false
  - ng e2e
  - npm run deploy

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
