os:
  - linux
services:
  - docker
  - xvfb
language: node_js
node_js:
  - "10.16.3"
addons:
  chrome: stable
branches:
  only:
  - develop
cache:
  directories:
    - node_modules
    - $(npm config get prefix)/bin/ng
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:90.0
  - npm install @angular/cli -g
install:
  - npm install
script:
  - ng test --watch false
  - ng e2e
  - npm run build
after_success:
  - 'test $TRAVIS_PULL_REQUEST = false && bash ./deploy.sh'

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
