os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.9.0"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
branches:
  only:
  - develop
cache:
  directories:
    - node_modules
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install @angular/cli -g
install:
  - npm install
script:
  - ng test --watch false
  - ng e2e
  - npm run build
after_success:
  - ./deploy.sh

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
